---
apiVersion: v1
kind: Service
metadata:
  name: pod-webhook
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: https-443
      port: 9443
      protocol: TCP
      targetPort: https
  sessionAffinity: None
  type: ClusterIP
