apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - newName: ccr.ccs.tencentyun.com/public-proxy/k8s-webhook
    name: image_name
    newTag: VERSION_TAG
commonLabels:
  app: k8s-webhook
kind: Kustomization
namespace: default
resources:
  - ../../base
